//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyGame.Bll.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrategyGame.Bll.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezt az országot már támadtad ebben a körben!.
        /// </summary>
        internal static string AlreadyAttackedCountry {
            get {
                return ResourceManager.GetString("AlreadyAttackedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilyen nevű ország már van!.
        /// </summary>
        internal static string AlreadyExistCountry {
            get {
                return ResourceManager.GetString("AlreadyExistCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezt a fejlesztést már kifejlesztetted!.
        /// </summary>
        internal static string AlreadyResearched {
            get {
                return ResourceManager.GetString("AlreadyResearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egy másik építkezés van folyamatban!.
        /// </summary>
        internal static string AnotherConstruction {
            get {
                return ResourceManager.GetString("AnotherConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egy másik fejlesztés van folyamatban!.
        /// </summary>
        internal static string AnotherResearch {
            get {
                return ResourceManager.GetString("AnotherResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs ilyen tipusú fejlesztés!.
        /// </summary>
        internal static string InvalidResearch {
            get {
                return ResourceManager.GetString("InvalidResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem sikerült a belépés!.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs elég Csata Csikód!.
        /// </summary>
        internal static string NotEnougCsataCsiko {
            get {
                return ResourceManager.GetString("NotEnougCsataCsiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs elég korallod!.
        /// </summary>
        internal static string NotEnoughCoral {
            get {
                return ResourceManager.GetString("NotEnoughCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs elég szállásod!.
        /// </summary>
        internal static string NotEnoughHousing {
            get {
                return ResourceManager.GetString("NotEnoughHousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs elég gyöngyöd!.
        /// </summary>
        internal static string NotEnoughPearl {
            get {
                return ResourceManager.GetString("NotEnoughPearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs elég Lézer Cápád!.
        /// </summary>
        internal static string NotEnougLezerCapa {
            get {
                return ResourceManager.GetString("NotEnougLezerCapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs elég Roham Fókád!.
        /// </summary>
        internal static string NotEnougRohamFoka {
            get {
                return ResourceManager.GetString("NotEnougRohamFoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem sikerült a regisztráció!.
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
    }
}
