// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyGame.Dal.Context;

namespace StrategyGame.Dal.Migrations
{
    [DbContext(typeof(StrategyGameContext))]
    partial class StrategyGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<Guid?>("OrszagId");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrszagId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Allapot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Kimenetel");

                    b.HasKey("Id");

                    b.ToTable("Allapots");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Csapat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CelpontId");

                    b.Property<int>("Kimenetel");

                    b.Property<long>("RaboltGyongy");

                    b.Property<long>("RaboltKorall");

                    b.Property<Guid?>("TulajdonosId");

                    b.HasKey("Id");

                    b.HasIndex("CelpontId");

                    b.HasIndex("TulajdonosId");

                    b.ToTable("Csapats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Egyseg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ar");

                    b.Property<Guid?>("CsapatId");

                    b.Property<Guid?>("CsapatId1");

                    b.Property<long>("CsatakSzama");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long>("Ellatas");

                    b.Property<long>("Szint");

                    b.Property<long>("Tamadas");

                    b.Property<long>("Vedekezes");

                    b.Property<long>("Zsold");

                    b.HasKey("Id");

                    b.HasIndex("CsapatId");

                    b.HasIndex("CsapatId1");

                    b.ToTable("Egysegs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Egyseg");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.EgysegInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ar");

                    b.Property<long>("CsatakSzama");

                    b.Property<long>("Ellatas");

                    b.Property<long>("KemkedesiKepesseg");

                    b.Property<long>("Szint");

                    b.Property<long>("Tamadas");

                    b.Property<int>("Tipus");

                    b.Property<long>("Vedekezes");

                    b.Property<long>("Zsold");

                    b.HasKey("Id");

                    b.ToTable("EgysegInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f9962e5-9a35-474b-bd45-c11e8d687532"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Tipus = 0,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("318d6138-0e33-497f-a277-512e4e4e531f"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Tipus = 1,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("e70a7b1c-2f9d-47c8-bcf8-e9cd11c3ee73"),
                            Ar = 100L,
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Tipus = 2,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("4bfde7e4-e515-46ca-b297-d5353400fecb"),
                            Ar = 50L,
                            CsatakSzama = 3L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 8L,
                            Tipus = 0,
                            Vedekezes = 3L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("720861fd-8605-400d-bd1a-064d05e26ee5"),
                            Ar = 50L,
                            CsatakSzama = 3L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 3L,
                            Tipus = 1,
                            Vedekezes = 8L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("e860325d-9183-45c3-b9bc-e752eced303e"),
                            Ar = 100L,
                            CsatakSzama = 3L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 7L,
                            Tipus = 2,
                            Vedekezes = 7L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("ed587e87-4128-4785-afb1-95000ef67d0e"),
                            Ar = 50L,
                            CsatakSzama = 8L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 10L,
                            Tipus = 0,
                            Vedekezes = 5L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("ca7d12d6-4060-43be-8996-9f83a5a90dd0"),
                            Ar = 50L,
                            CsatakSzama = 8L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 5L,
                            Tipus = 1,
                            Vedekezes = 10L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("6d6919dc-bcfc-40f7-bf8c-7b9be7efb70a"),
                            Ar = 100L,
                            CsatakSzama = 8L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 10L,
                            Tipus = 2,
                            Vedekezes = 10L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("12ca7cbc-1a7c-4c7e-848d-00b91ce90b61"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 5L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Tipus = 3,
                            Vedekezes = 0L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.Epulet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AktualisKor");

                    b.Property<long>("Ar");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("Felepult");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("SzuksegesKorok");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Epulets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Epulet");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AktualisKor");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("Kifejlesztve");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("SzuksegesKorok");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Fejleszteses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Fejlesztes");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Felfedezes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CelpontId");

                    b.Property<long>("Gyongy");

                    b.Property<DateTime>("Idopont");

                    b.Property<long>("Korall");

                    b.Property<long>("VedekezoEro");

                    b.HasKey("Id");

                    b.HasIndex("CelpontId");

                    b.ToTable("Felfedezes");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Jatek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Korok");

                    b.HasKey("Id");

                    b.ToTable("Jateks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d543ba28-ac1e-4ae0-a89f-b4173cb56222"),
                            Korok = 0L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long>("Ertek");

                    b.Property<Guid>("FejlesztesId");

                    b.HasKey("Id");

                    b.HasIndex("FejlesztesId");

                    b.ToTable("AbstractNovelo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.NoveloInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ertek");

                    b.Property<int>("Tipus");

                    b.HasKey("Id");

                    b.ToTable("NoveloInfos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Orszag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Gyongy");

                    b.Property<long>("Korall");

                    b.Property<string>("Nev");

                    b.Property<long>("Pont");

                    b.HasKey("Id");

                    b.ToTable("Orszags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Gyongy = 4070L,
                            Korall = 1839L,
                            Nev = "Tesztorszag0",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Gyongy = 1422L,
                            Korall = 1126L,
                            Nev = "Tesztorszag1",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Gyongy = 4490L,
                            Korall = 731L,
                            Nev = "Tesztorszag2",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Gyongy = 4652L,
                            Korall = 1884L,
                            Nev = "Tesztorszag3",
                            Pont = 0L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("EgysegTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("KorallTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("NepessegTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.CsataCsiko", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("CsataCsiko");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2af62933-cd0d-42f8-b5e0-32cfa3ee72b8"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("6515cec6-ca9f-4883-b768-3c6130446e10"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("837ff8c7-daf7-41bb-9816-c24fd12aa722"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("c7b6fe78-24c9-4b1a-98e4-84a639ba7d3d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("b4ebc367-96e6-4740-a9c7-aaaa59ef47f8"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("18bafe8b-0094-45dd-9893-b93287d35d43"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("a9d3b459-51c5-4e6d-ae6c-568428065ac6"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("2ef35298-34ca-49d3-8fd6-6aeade9ace23"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("de7bf337-c9eb-47bf-b1ec-8f9534fa899f"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("a9d44ce3-420d-46de-b1cb-2a1676dbdd50"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("f23f879c-39e0-4574-9100-e85481514d7a"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("d1aa568c-5139-4f4f-b692-d693af1fd9e9"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("92d26bf1-b59f-41f8-a73f-1e6d22222c93"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("683dd8a6-faca-41fe-82e2-9eae098de614"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("3171a482-7f45-4383-a779-b20218f46091"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("45d87cec-86bd-4ed4-b7d8-4a7e4c18aac6"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("1ab576cf-6f1e-4127-ad2a-19f87dcc79c1"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("d31f3403-2746-4d76-83b0-42b952ab50c8"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Felfedezo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.Property<bool>("Felfedezett");

                    b.Property<long>("KemkedesiKepesseg");

                    b.HasDiscriminator().HasValue("Felfedezo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07010cec-f996-4f2e-97bb-91b6ccd3917d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("e908c3bb-9e5e-41fa-b165-f509b45d8cee"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("dd8e68f3-f0e3-4b02-b56e-d0f60efb2e5e"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("b4c320c7-ae58-4922-b7c8-3f6415991435"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("82ddf320-1b45-4853-ae4d-81afe2a7954d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("16666703-e0a9-4dc0-af57-14138339a9ab"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("6a44b601-a2e8-4562-bdfb-2863a49a1aeb"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("d949e704-decb-4f4b-8a76-ac78daa2c818"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("001eb5a0-4d04-46b1-8078-55056be4fb20"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("16219883-acf9-4393-ba03-83606436cc80"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("7248c955-cb1c-4298-93e8-90347b90e784"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("e0c661f2-8f3f-4fa9-b2dc-f93236afaccd"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("914ae697-955b-480e-a6ed-d7c8372d51ee"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("8997ee67-ebdd-48d0-9859-a53435ec4557"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("513a7828-7170-4edd-a77c-479579b1a117"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("232907c3-e51c-4bf1-8db2-1e8838ac621e"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("680b1f9a-d798-4594-bbc1-80212868f57a"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("5c298a5d-4a9d-4207-a6c3-e9532e859edf"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("af439017-d09c-454d-9a2d-e63080801d15"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("1deab0d3-8d7e-4396-beef-c86637e50cd7"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("c65fdf6e-f79a-4669-b462-765f79657afa"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("4f9cb03c-48a6-4941-97a1-76ca073d82a7"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.LezerCapa", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("LezerCapa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb6bf72f-ac9d-4826-a395-5ebe69a7a945"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("70135007-fbbd-43be-b308-cb94aae29619"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("74a77e2d-9d46-4c75-a502-f0688083ca83"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("6e3ce38d-e4c1-4c03-977a-26f30c796b52"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("a5207e77-b25f-4491-842b-c47bcdff9e6b"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("2888d21b-e19e-461c-a4ce-a50750a3fd54"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("fa6bcf62-d82e-4b0e-894d-374833aa3840"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("4b2cb557-6589-4aad-b9c0-c2688b24d5a1"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("d0b087af-ef86-4721-ae16-33f30528d862"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("5bc09c92-b136-4c95-bb69-fd1533983377"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("f3ec8bba-2c08-41e4-8747-0d407f22d885"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("25eef147-6e99-4c9a-8081-fdb705badb2b"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("520708cf-a591-4883-80d0-0c22c3f8e156"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.RohamFoka", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("RohamFoka");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc66ba54-e0c3-4fb8-93de-794b792b358d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("c2181c33-0b01-43da-b9e1-94c2481dc9f0"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("046b7b9e-7067-4cfd-9d0a-6c2d0f1d38e4"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("6696755f-49b5-449f-988a-327edf91cd0a"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("078e55fc-f2f8-4377-89ca-ba03e8640e73"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("f33e4c14-84be-4033-a4ed-b2d0a6ef423d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("542d75bd-2ae6-40b8-9c7e-766a62fea06d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("783de50a-3895-473e-ac4c-c0fb9b9e9df4"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("cf29d2dc-da99-4238-a9e0-9864170ba0ea"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("e7237e20-a0d1-4210-813a-1922ee069db0"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("3feb61e2-5c9b-4a91-9213-f6350d703b2c"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("12354362-4c47-44d9-bb88-c68012c41967"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("727c979f-23e4-464e-80b8-f054562e3d67"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("1d664c3a-7e15-44b6-bc01-7f90c4720e80"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("1410c480-537b-4a7d-9d71-140c4ca349b1"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("5c0f6be8-575f-4f31-88ad-f1688ee5ebbd"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("005adad3-8d7d-4f05-9237-aebe6082fcb4"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("b7139fde-7d6c-4ac9-bf87-1fa3d767028d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("216114ee-4ac6-49ff-b150-9654067e166b"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("46c2b7a1-1e30-4d3c-9071-9232f95840a2"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("81f32969-103a-46a9-a471-b7185cc6abb5"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("2fdb4326-c1e4-434b-9d96-cb79cdf3c921"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Epuletek.Epulet");

                    b.HasDiscriminator().HasValue("AramlasIranyito");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54c60832-b555-45bc-91e8-e32b3d8e76f8"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("f62591d8-211a-46f2-9533-99e33faee44b"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("5f37f875-d34d-43b8-a91b-04c20df70443"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("f5979765-8939-4b35-95de-d38aef646137"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SzuksegesKorok = 15L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.ZatonyVar", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Epuletek.Epulet");

                    b.HasDiscriminator().HasValue("ZatonyVar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f1bf0ff-35be-404d-8288-f8d5576155e9"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("efd6fdce-a485-4268-b25e-235f6f931cad"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("30879c33-fffe-4c8e-81a3-3a5c1643c4af"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("76e588da-72c8-46c9-87cc-696fea50924e"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SzuksegesKorok = 15L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Alkimia", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("Alkimia");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.IszapKombajn", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("IszapKombajn");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.IszapTraktor", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("IszapTraktor");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.KorallFal", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("KorallFal");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.SzonarAgyu", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("SzonarAgyu");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.VizalattiHarcmuveszet", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("VizalattiHarcmuveszet");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AdoNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("AdoNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.KorallNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("KorallNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.TamadasNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("TamadasNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.VedekezesNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("VedekezesNovelo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameUser", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany()
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Csapat", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Celpont")
                        .WithMany("TamadoCsapats")
                        .HasForeignKey("CelpontId");

                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Tulajdonos")
                        .WithMany("OtthoniCsapats")
                        .HasForeignKey("TulajdonosId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Egyseg", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Csapat")
                        .WithMany("Egysegs")
                        .HasForeignKey("CsapatId");

                    b.HasOne("StrategyGame.Model.Entities.Models.Csapat")
                        .WithMany("VedekezoEgysegs")
                        .HasForeignKey("CsapatId1");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.Epulet", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Epulets")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Fejleszteses")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Felfedezes", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Celpont")
                        .WithMany("Felfedezeses")
                        .HasForeignKey("CelpontId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", "Fejlesztes")
                        .WithMany("Novelo")
                        .HasForeignKey("FejlesztesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.ZatonyVar", "Epulet")
                        .WithOne("Szallas")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", "Epulet")
                        .WithOne("Korall")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", "Epulet")
                        .WithOne("Nepesseg")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
