// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyGame.Dal.Context;

namespace StrategyGame.Dal.Migrations
{
    [DbContext(typeof(StrategyGameContext))]
    partial class StrategyGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<Guid?>("OrszagId");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrszagId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Allapot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Kimenetel");

                    b.HasKey("Id");

                    b.ToTable("Allapots");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Csapat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CelpontId");

                    b.Property<int>("Kimenetel");

                    b.Property<long>("RaboltGyongy");

                    b.Property<long>("RaboltKorall");

                    b.Property<Guid?>("TulajdonosId");

                    b.HasKey("Id");

                    b.HasIndex("CelpontId");

                    b.HasIndex("TulajdonosId");

                    b.ToTable("Csapats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Egyseg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ar");

                    b.Property<Guid?>("CsapatId");

                    b.Property<Guid?>("CsapatId1");

                    b.Property<long>("CsatakSzama");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long>("Ellatas");

                    b.Property<long>("Szint");

                    b.Property<long>("Tamadas");

                    b.Property<long>("Vedekezes");

                    b.Property<long>("Zsold");

                    b.HasKey("Id");

                    b.HasIndex("CsapatId");

                    b.HasIndex("CsapatId1");

                    b.ToTable("Egysegs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Egyseg");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.EgysegInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ar");

                    b.Property<long>("CsatakSzama");

                    b.Property<long>("Ellatas");

                    b.Property<long>("KemkedesiKepesseg");

                    b.Property<long>("Szint");

                    b.Property<long>("Tamadas");

                    b.Property<int>("Tipus");

                    b.Property<long>("Vedekezes");

                    b.Property<long>("Zsold");

                    b.HasKey("Id");

                    b.ToTable("EgysegInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ebf0cdbb-a5fe-47b4-94b6-dccf92d9fa42"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Tipus = 0,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("456694e9-0b59-449d-992a-3256d8fdd83a"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Tipus = 1,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("a38645c9-c027-4168-a840-2d46c47a5797"),
                            Ar = 100L,
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Tipus = 2,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("f609c161-75b3-40b0-bf6f-d3d9d1939552"),
                            Ar = 50L,
                            CsatakSzama = 3L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 8L,
                            Tipus = 0,
                            Vedekezes = 3L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("0629af74-75bc-4f91-a2dd-a6cdef4c214f"),
                            Ar = 50L,
                            CsatakSzama = 3L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 3L,
                            Tipus = 1,
                            Vedekezes = 8L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("078e1a06-365a-4931-b6f1-5b5f65f7e080"),
                            Ar = 100L,
                            CsatakSzama = 3L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 7L,
                            Tipus = 2,
                            Vedekezes = 7L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("7ff62a32-3167-4bb7-8228-e7f76a6dd073"),
                            Ar = 50L,
                            CsatakSzama = 8L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 10L,
                            Tipus = 0,
                            Vedekezes = 5L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("fa26dc57-7198-4eea-ba50-ec79bc6364bc"),
                            Ar = 50L,
                            CsatakSzama = 8L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 5L,
                            Tipus = 1,
                            Vedekezes = 10L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("00125a79-6dd3-4261-b6fd-24546c3a0732"),
                            Ar = 100L,
                            CsatakSzama = 8L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 10L,
                            Tipus = 2,
                            Vedekezes = 10L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("6b0075c9-1985-4108-a2c6-79ef92e2f01e"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 5L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Tipus = 3,
                            Vedekezes = 0L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.Epulet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AktualisKor");

                    b.Property<long>("Ar");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("Felepult");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("SzuksegesKorok");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Epulets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Epulet");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AktualisKor");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("Kifejlesztve");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("SzuksegesKorok");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Fejleszteses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Fejlesztes");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Felfedezes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celpont");

                    b.Property<long>("Gyongy");

                    b.Property<DateTime>("Idopont");

                    b.Property<long>("Korall");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("VedekezoEro");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Felfedezeses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000005"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 3, 15, 22, 41, 931, DateTimeKind.Local).AddTicks(7975),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            VedekezoEro = 666L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000006"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 3, 15, 22, 41, 936, DateTimeKind.Local).AddTicks(5347),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            VedekezoEro = 666L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000007"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 3, 15, 22, 41, 936, DateTimeKind.Local).AddTicks(6834),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            VedekezoEro = 666L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000008"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 3, 15, 22, 41, 936, DateTimeKind.Local).AddTicks(8065),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            VedekezoEro = 666L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Jatek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Korok");

                    b.HasKey("Id");

                    b.ToTable("Jateks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("020b810c-7453-4788-9d3a-75c3cdf2ac99"),
                            Korok = 0L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long>("Ertek");

                    b.Property<Guid>("FejlesztesId");

                    b.HasKey("Id");

                    b.HasIndex("FejlesztesId");

                    b.ToTable("AbstractNovelo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.NoveloInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ertek");

                    b.Property<int>("Tipus");

                    b.HasKey("Id");

                    b.ToTable("NoveloInfos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Orszag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Gyongy");

                    b.Property<long>("Korall");

                    b.Property<string>("Nev");

                    b.Property<long>("Pont");

                    b.HasKey("Id");

                    b.ToTable("Orszags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Gyongy = 2424L,
                            Korall = 993L,
                            Nev = "Tesztorszag0",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Gyongy = 4101L,
                            Korall = 1565L,
                            Nev = "Tesztorszag1",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Gyongy = 1764L,
                            Korall = 610L,
                            Nev = "Tesztorszag2",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Gyongy = 4437L,
                            Korall = 1617L,
                            Nev = "Tesztorszag3",
                            Pont = 0L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("EgysegTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("KorallTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("NepessegTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.CsataCsiko", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("CsataCsiko");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd00481b-38b3-4ce4-b5c2-e5b2185dca53"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("01282228-420b-4e9b-ab1f-5e9f790a7ce7"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("b1e4a711-0015-4a42-a4bd-d9e0fa426f38"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("a4570101-f53b-477a-8bb2-2737bf0fdd34"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("d0df277d-febd-49ec-9aa1-e9672145a603"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("fa1191b8-6d65-4ddf-9a71-6eed8a3fc140"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("847dbbac-1561-4c6a-a94d-1f5e281446ba"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("8479e001-69b8-4f1f-babd-443685ad7b72"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("6c59c7f7-e4e6-4000-9ca4-687ed1fafcdc"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("f808c8ad-c034-48d9-8396-a67fe7659fec"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("aa9f6cc9-da1d-4c82-ae92-b646de12abad"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("e755c3d2-84f3-40a0-aea6-42d075a6a6f8"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Felfedezo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.Property<bool>("Felfedezett");

                    b.Property<long>("KemkedesiKepesseg");

                    b.HasDiscriminator().HasValue("Felfedezo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c913afd-0818-419f-8620-14dd46d7c43f"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("a62c7c65-6802-4e19-a0ba-ee43e0ec19ed"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("150c29cf-cefa-4bb0-9385-bf7389d464a2"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("c0e1277b-0a95-45f3-807c-f3de7f5cedba"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("8c5c348f-c4e3-4d22-8872-f9e064a47c59"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("a61deb67-ace1-4afe-a9c7-73a5e445bfea"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("6c11b793-320f-4c62-b3a2-791a7aa269ff"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("2f213391-6b59-4ab5-b0c7-962794c6b5dd"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("483eaff5-8bc5-414b-8fea-f1c790daafc3"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("7d129950-44ac-4f18-901e-e526748595d3"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("fd46b44a-3653-4c98-9ecf-cf47616594d9"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("17951a01-f8dd-4c29-a143-369b51913906"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("ee1436e6-e60c-443a-a793-50c7f9d176eb"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("b70f2c88-2ec2-4a17-9ece-0d55c6ef528d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("7d0433cd-af41-439d-9463-60879e864e42"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("10bff0e3-0db7-48e0-bcd2-21d484128d9d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("cb073a4e-8f86-47d9-b996-6471dc64f425"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("2ee2c7b2-7606-4811-8339-75fbc0896d7a"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.LezerCapa", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("LezerCapa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0f6ea7b-8dc6-42e7-9784-7ef722e9cbf5"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("eb90f005-5702-43e7-b6dc-ad5982353902"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("c7d6c9f8-a58c-4e4a-b937-ac7842e52cdf"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("fc91329a-f41d-414b-9906-f5a80ac66776"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("8361f6d6-9f96-461c-a38a-417a1c51d623"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("a0c0e5bc-28f2-48f3-a4d3-6d6f4f1ef735"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("5b08a228-fba2-4c3b-8de8-b2184a53ddb5"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.RohamFoka", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("RohamFoka");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a6061d7-0a78-40a6-962c-b24861dca375"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("f363c25c-bcaf-422c-afc2-9256c444d18b"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("b8d16526-537d-43ba-8799-29daab35788d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("3e61d1b6-bdef-4f12-a5ee-c2d5d18a58f1"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("3bad20b6-4218-4372-a5eb-32488626b5be"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("7e7c77de-cb2b-4a49-b438-64de2164ad10"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("0f76e045-0596-4167-a5af-9914609d9141"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("44b79830-ee29-46ea-89e3-dc6b06156e6f"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("4002e24d-1f00-4a49-bf3e-31df392b20d2"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("692baabb-b867-4ed0-b483-cff2c8a00307"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("9796cdcf-2237-4105-acc7-abe8782c94e3"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("89c4b3a9-b06d-4c22-be08-5c616cc38fdd"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("55552ab2-aa72-4a21-96a2-5d3a177c67ff"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Epuletek.Epulet");

                    b.HasDiscriminator().HasValue("AramlasIranyito");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68516f9f-1138-4c2b-82fa-9c817d74769e"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("c7a5ddb4-884b-45c1-a241-dfe0b743b7ca"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("6640938d-5424-4baa-ab81-e0266ae86a99"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("b8edb092-42d4-4a27-87dc-564da15ba604"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SzuksegesKorok = 15L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.ZatonyVar", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Epuletek.Epulet");

                    b.HasDiscriminator().HasValue("ZatonyVar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12abbcf6-454c-43cd-a163-18e632306fd6"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("4b5e04de-e662-4065-a1e3-211555c0b883"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("bd8a282a-3746-4ccb-89d0-782ba7b7f6a7"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("91a30a37-ab06-43d0-9083-a7899b7bc80f"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SzuksegesKorok = 15L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Alkimia", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("Alkimia");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.IszapKombajn", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("IszapKombajn");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.IszapTraktor", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("IszapTraktor");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.KorallFal", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("KorallFal");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.SzonarAgyu", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("SzonarAgyu");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.VizalattiHarcmuveszet", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("VizalattiHarcmuveszet");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AdoNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("AdoNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.KorallNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("KorallNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.TamadasNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("TamadasNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.VedekezesNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("VedekezesNovelo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameUser", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany()
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Csapat", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Celpont")
                        .WithMany("TamadoCsapats")
                        .HasForeignKey("CelpontId");

                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Tulajdonos")
                        .WithMany("OtthoniCsapats")
                        .HasForeignKey("TulajdonosId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Egyseg", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Csapat")
                        .WithMany("Egysegs")
                        .HasForeignKey("CsapatId");

                    b.HasOne("StrategyGame.Model.Entities.Models.Csapat")
                        .WithMany("VedekezoEgysegs")
                        .HasForeignKey("CsapatId1");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.Epulet", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Epulets")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Fejleszteses")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Felfedezes", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Felfedezeses")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", "Fejlesztes")
                        .WithMany("Novelo")
                        .HasForeignKey("FejlesztesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.ZatonyVar", "Epulet")
                        .WithOne("Szallas")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", "Epulet")
                        .WithOne("Korall")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", "Epulet")
                        .WithOne("Nepesseg")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
