// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyGame.Dal.Context;

namespace StrategyGame.Dal.Migrations
{
    [DbContext(typeof(StrategyGameContext))]
    partial class StrategyGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<Guid?>("OrszagId");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrszagId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Allapot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Kimenetel");

                    b.HasKey("Id");

                    b.ToTable("Allapots");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Csapat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CelpontId");

                    b.Property<int>("Kimenetel");

                    b.Property<long>("RaboltGyongy");

                    b.Property<long>("RaboltKorall");

                    b.Property<Guid?>("TulajdonosId");

                    b.HasKey("Id");

                    b.HasIndex("CelpontId");

                    b.HasIndex("TulajdonosId");

                    b.ToTable("Csapats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Kimenetel = 4,
                            RaboltGyongy = 0L,
                            RaboltKorall = 0L,
                            TulajdonosId = new Guid("00000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Egyseg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ar");

                    b.Property<Guid?>("CsapatId");

                    b.Property<Guid?>("CsapatId1");

                    b.Property<long>("CsatakSzama");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long>("Ellatas");

                    b.Property<long>("Szint");

                    b.Property<long>("Tamadas");

                    b.Property<long>("Vedekezes");

                    b.Property<long>("Zsold");

                    b.HasKey("Id");

                    b.HasIndex("CsapatId");

                    b.HasIndex("CsapatId1");

                    b.ToTable("Egysegs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Egyseg");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.EgysegInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ar");

                    b.Property<long>("CsatakSzama");

                    b.Property<long>("Ellatas");

                    b.Property<long>("KemkedesiKepesseg");

                    b.Property<long>("Szint");

                    b.Property<long>("Tamadas");

                    b.Property<int>("Tipus");

                    b.Property<long>("Vedekezes");

                    b.Property<long>("Zsold");

                    b.HasKey("Id");

                    b.ToTable("EgysegInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29c9aab0-7246-48e8-bd54-dee63aabac11"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Tipus = 0,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("3edd4c45-1bcb-4c6e-8353-857ff4d58876"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Tipus = 1,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("f1324abb-cb91-4412-87da-4a27be34df1b"),
                            Ar = 100L,
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Tipus = 2,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("3f910110-4aba-4dc1-905c-34a53afd3972"),
                            Ar = 50L,
                            CsatakSzama = 3L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 8L,
                            Tipus = 0,
                            Vedekezes = 3L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("91ed9370-8a66-427f-81b3-72ff023fa468"),
                            Ar = 50L,
                            CsatakSzama = 3L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 3L,
                            Tipus = 1,
                            Vedekezes = 8L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("e955efac-c78f-44ea-ada7-89b7ac28a98d"),
                            Ar = 100L,
                            CsatakSzama = 3L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 2L,
                            Tamadas = 7L,
                            Tipus = 2,
                            Vedekezes = 7L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("eca503a0-a7db-4c43-90db-86ad9ceeb66f"),
                            Ar = 50L,
                            CsatakSzama = 8L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 10L,
                            Tipus = 0,
                            Vedekezes = 5L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("976c5663-184d-4679-9a7e-8aafab2acdbd"),
                            Ar = 50L,
                            CsatakSzama = 8L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 5L,
                            Tipus = 1,
                            Vedekezes = 10L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("89378668-6a1a-4311-86fd-345266d1ab1f"),
                            Ar = 100L,
                            CsatakSzama = 8L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 3L,
                            Tamadas = 10L,
                            Tipus = 2,
                            Vedekezes = 10L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("8208d5f1-f15c-4ee3-9839-8dcd0bd2d99e"),
                            Ar = 50L,
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            KemkedesiKepesseg = 5L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Tipus = 3,
                            Vedekezes = 0L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("3a8e0cc8-a3b9-4ff7-b318-6531e76c959a"),
                            Ar = 200L,
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            KemkedesiKepesseg = 0L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Tipus = 4,
                            Vedekezes = 0L,
                            Zsold = 4L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.Epulet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AktualisKor");

                    b.Property<long>("Ar");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("Felepult");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("SzuksegesKorok");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Epulets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Epulet");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AktualisKor");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("Kifejlesztve");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("SzuksegesKorok");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Fejleszteses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Fejlesztes");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Felfedezes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celpont");

                    b.Property<long>("Gyongy");

                    b.Property<DateTime>("Idopont");

                    b.Property<long>("Korall");

                    b.Property<Guid?>("OrszagId");

                    b.Property<long>("VedekezoEro");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.ToTable("Felfedezeses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000005"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 4, 9, 45, 27, 200, DateTimeKind.Local).AddTicks(9253),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            VedekezoEro = 666L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000006"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 4, 9, 45, 27, 204, DateTimeKind.Local).AddTicks(4533),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            VedekezoEro = 666L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000007"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 4, 9, 45, 27, 204, DateTimeKind.Local).AddTicks(7031),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            VedekezoEro = 666L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-003000000008"),
                            Celpont = "asd",
                            Gyongy = 1000L,
                            Idopont = new DateTime(2019, 7, 4, 9, 45, 27, 204, DateTimeKind.Local).AddTicks(8359),
                            Korall = 999L,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            VedekezoEro = 666L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Jatek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Korok");

                    b.HasKey("Id");

                    b.ToTable("Jateks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("997ab8f5-0096-4eb0-a81c-3aeef6b111b3"),
                            Korok = 0L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long>("Ertek");

                    b.Property<Guid>("FejlesztesId");

                    b.HasKey("Id");

                    b.HasIndex("FejlesztesId");

                    b.ToTable("AbstractNovelo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.NoveloInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ertek");

                    b.Property<int>("Tipus");

                    b.HasKey("Id");

                    b.ToTable("NoveloInfos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Orszag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Gyongy");

                    b.Property<long>("Korall");

                    b.Property<string>("Nev");

                    b.Property<long>("Pont");

                    b.HasKey("Id");

                    b.ToTable("Orszags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Gyongy = 4501L,
                            Korall = 1140L,
                            Nev = "Tesztorszag0",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Gyongy = 4594L,
                            Korall = 200L,
                            Nev = "Tesztorszag1",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Gyongy = 2410L,
                            Korall = 1025L,
                            Nev = "Tesztorszag2",
                            Pont = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Gyongy = 3953L,
                            Korall = 1889L,
                            Nev = "Tesztorszag3",
                            Pont = 0L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("EgysegTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("KorallTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EpuletId");

                    b.Property<long>("Ertek");

                    b.HasKey("Id");

                    b.HasIndex("EpuletId")
                        .IsUnique();

                    b.ToTable("NepessegTermelos");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.CsataCsiko", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("CsataCsiko");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c6e8050-3b56-48ee-babe-51979053d00f"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("a0eef949-e9c9-4faa-add5-38ce74aea04b"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("6730e675-e377-4c60-b37d-dfabf8ba1dca"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("44987436-0e8b-4049-be84-96c063019733"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("51824fa6-0fa9-463c-9670-4bb49b011dfe"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("344f2ffc-c9f8-4e96-9a55-edf4d9ad6cff"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("293f1475-36ba-45de-9e7c-9ada754b992c"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("f8d2a7c2-a9e1-476d-9f95-e73601377c82"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("b6170072-7811-41ac-999a-e86d32ffbf6d"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("047cff03-12c5-4606-aeb9-841678e97ce2"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("caadf494-7d17-41ba-ac6a-c2b819f84852"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("810a57d5-b8fe-4194-9251-28460eeb0f71"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("29c78ffe-8ee1-4543-8ea2-d040b53e88e0"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("f35d407f-fd15-485e-9672-9fe6b0e4e8c7"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("2a9e4793-9ac3-4caa-814a-60b215cf7ab5"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 2L,
                            Vedekezes = 6L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Felfedezo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.Property<bool>("Felfedezett");

                    b.Property<long>("KemkedesiKepesseg");

                    b.HasDiscriminator().HasValue("Felfedezo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f37e8d7d-32b3-4d58-a2bc-1fad28bb7416"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("7ca6f1af-675d-4ab5-9d29-7ac61214b549"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("b309eab2-ae9d-4386-bb4e-10ed568aaa02"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("d442c81f-cf4e-4322-9215-3c95001ef159"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("48ce18d4-6ea2-48fc-bf62-6671d75ea744"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("1467bf06-9820-4d29-9ba8-24dd93c27932"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("88b555e5-5fd4-4e88-9ff4-9165051ead03"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("739cfc41-b134-4ff7-afe2-88e2b17b632f"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("fd2b6a4a-4a84-4f2d-a409-d4e0b0b0250f"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("14ccfb7d-9435-489e-8430-6d51c356eaba"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("49a4e3b2-f02d-4919-bf06-7d68d1c7f752"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("df446854-8bba-4159-b301-c8f8137c0aa6"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("dcf28ba5-2c14-47ef-9a42-70982c99905e"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("f9d428f1-38d2-4de2-a98f-2995347ecfc0"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("431498e9-121f-4b5a-81ca-319b5cde95aa"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("4a36bae8-928b-483d-8202-62c8837a3799"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("cde12abd-e215-4d92-97a6-455291276989"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("fa95d499-df7c-4189-85a6-fcadaa9d4b08"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("2134b54b-2b0a-41e7-8c93-ba4c6ff2945c"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        },
                        new
                        {
                            Id = new Guid("fefb6b80-b5ee-4737-87b5-d7283121ad65"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 1L,
                            Felfedezett = false,
                            KemkedesiKepesseg = 5L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Hadvezer", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("Hadvezer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c85e6cb-5782-4c5f-8d52-c1afdda78cc6"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("8d0eb1b5-9f53-40bc-82e3-135563fb7631"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("9ec7e3b7-c1c9-466b-a59f-86f466f257b4"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("f0cdea07-9d95-4fa3-848d-e469ee13397d"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("2e06de74-e535-4463-ad92-43f1170744f7"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("77e879c8-0585-478b-9d02-31786ee6779d"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("62b50b4b-1c4d-48ef-8255-c2b51c101cb1"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("26bfca60-fe7c-41fe-b2a7-d6a4e831b403"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("730e0e0f-1d63-41c7-9c8e-52f5672913f3"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        },
                        new
                        {
                            Id = new Guid("94185e10-2989-4071-a48e-b4da257fd74f"),
                            Ar = 200L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 0L,
                            Vedekezes = 0L,
                            Zsold = 4L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.LezerCapa", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("LezerCapa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abdd01cc-d066-4276-ba68-2f7817ef3eb3"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("0ca4e9fe-da9e-443b-91d3-da2b7b821980"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("a675971d-6bfb-4bc8-b646-679b3f0389d0"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("bd82d8d8-c443-4367-87e4-306988300ac1"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("0a157c65-5104-44fa-b21f-c50098605d72"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("e3f5a495-6f1c-4b85-9b02-4431359b56da"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("33b94dcd-5194-4d34-a179-fae95b2eeb49"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("3c5c901d-0939-4424-b207-2e49a4f02576"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("62df3d34-7a03-4123-9228-6659187a51d9"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("05c7cb37-843a-4a49-b8cd-4cd7a8e64b88"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("59ed3897-a6b6-46f4-a9be-42646532e78b"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("f05721ad-c7ae-4147-a01c-125c11c0f5c5"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("136994ef-a448-4a48-82f2-b93b1014e873"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("ca10b9c3-4ae4-45fa-939e-c78ab2a922d3"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        },
                        new
                        {
                            Id = new Guid("f81f2ef4-efed-4332-883b-420beda2608d"),
                            Ar = 100L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 2L,
                            Szint = 1L,
                            Tamadas = 5L,
                            Vedekezes = 5L,
                            Zsold = 3L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.RohamFoka", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Egysegek.Egyseg");

                    b.HasDiscriminator().HasValue("RohamFoka");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c7e6170-1459-4fcd-95c3-c1cfb1d688cf"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("cb25c8e3-006e-4617-b789-51928f1340e3"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("c613515c-3a40-48a8-a356-ae0cc39a88bf"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("9dc6dab5-e376-491f-94d9-31bfc63610cd"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("37ba4253-ec39-4ef5-bbf5-2213e1ae36b9"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("292ce4de-4609-4fda-8013-5ee00977c246"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("b93bc892-6dd0-40fb-88f2-6fdb36df9ad0"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("882df22d-8dd4-40b9-bfc0-21d71d164d6a"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000006"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("fd32cb8f-f138-4f4a-bdbb-84221f31df29"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("5d904919-514a-4558-924d-1c488851207a"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000007"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("3131156c-0cc7-48c8-a85f-f45aaad2a6bf"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        },
                        new
                        {
                            Id = new Guid("c4d2e54d-f12b-4890-905a-eb75f199ba44"),
                            Ar = 50L,
                            CsapatId = new Guid("00000000-0000-0000-0000-000000000008"),
                            CsatakSzama = 0L,
                            Ellatas = 1L,
                            Szint = 1L,
                            Tamadas = 6L,
                            Vedekezes = 2L,
                            Zsold = 1L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Epuletek.Epulet");

                    b.HasDiscriminator().HasValue("AramlasIranyito");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34936abc-ca4b-41b8-aa7c-72a695b3ad45"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("e9a7ab17-7375-4e6a-90e7-962995f723a6"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("5d844964-2b95-4813-a672-4896085230af"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("2ebcd3b8-d71d-4cbf-9ab6-e6526df18f3e"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SzuksegesKorok = 15L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.ZatonyVar", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Epuletek.Epulet");

                    b.HasDiscriminator().HasValue("ZatonyVar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae714325-798c-464b-8b63-5306bb4b78b7"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("269b6d65-5ad1-47a9-82c1-9e6e5704aa76"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("71c6e332-5749-4359-a606-57ba9b7df40b"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SzuksegesKorok = 15L
                        },
                        new
                        {
                            Id = new Guid("2b1832d1-5048-4253-8990-4738dbeb93bd"),
                            AktualisKor = 15L,
                            Ar = 1000L,
                            Felepult = true,
                            OrszagId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SzuksegesKorok = 15L
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Alkimia", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("Alkimia");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.IszapKombajn", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("IszapKombajn");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.IszapTraktor", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("IszapTraktor");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.KorallFal", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("KorallFal");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.SzonarAgyu", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("SzonarAgyu");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.VizalattiHarcmuveszet", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes");

                    b.HasDiscriminator().HasValue("VizalattiHarcmuveszet");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AdoNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("AdoNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.KorallNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("KorallNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.TamadasNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("TamadasNovelo");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.VedekezesNovelo", b =>
                {
                    b.HasBaseType("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo");

                    b.HasDiscriminator().HasValue("VedekezesNovelo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Identity.StrategyGameUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Identity.StrategyGameUser", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany()
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Csapat", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Celpont")
                        .WithMany("TamadoCsapats")
                        .HasForeignKey("CelpontId");

                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Tulajdonos")
                        .WithMany("OtthoniCsapats")
                        .HasForeignKey("TulajdonosId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Egysegek.Egyseg", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Csapat")
                        .WithMany("Egysegs")
                        .HasForeignKey("CsapatId");

                    b.HasOne("StrategyGame.Model.Entities.Models.Csapat")
                        .WithMany("VedekezoEgysegs")
                        .HasForeignKey("CsapatId1");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Epuletek.Epulet", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Epulets")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Fejleszteses")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Felfedezes", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Orszag", "Orszag")
                        .WithMany("Felfedezeses")
                        .HasForeignKey("OrszagId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Novelok.AbstractNovelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Fejlesztesek.Fejlesztes", "Fejlesztes")
                        .WithMany("Novelo")
                        .HasForeignKey("FejlesztesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.ZatonyVar", "Epulet")
                        .WithOne("Szallas")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.EgysegTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", "Epulet")
                        .WithOne("Korall")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.KorallTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Models.Epuletek.AramlasIranyito", "Epulet")
                        .WithOne("Nepesseg")
                        .HasForeignKey("StrategyGame.Model.Entities.Models.Termelok.NepessegTermelo", "EpuletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
